client_id = "101788b0d255dbcf49ca90c5e287672a"
name = "SuprImg: Anti-theft Watermark"
handle = "suprimg"
application_url = "https://suprimg.gadget.app"
embedded = true

[build]
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://suprimg--development.gadget.app/api/connections/auth/shopify/callback",
  "https://suprimg.gadget.app/api/connections/auth/shopify/callback"
]

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  uri = "https://suprimg.gadget.app/api/webhooks/shopify"
  compliance_topics = [ "customers/redact", "customers/data_request", "shop/redact" ]

[pos]
embedded = false
