# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ff2b44ceaeb615cd269f256f7a052b56"
name = "SuprImg Dev"
handle = "suprimg-dev"
application_url = "https://suprimg--development.gadget.app/"
embedded = true

[build]
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products, write_products"

[auth]
redirect_urls = [
  "https://suprimg--development.gadget.app/api/connections/auth/shopify/callback"
]

[webhooks]
api_version = "2025-04"

[pos]
embedded = false
